version: '3.8'

services:
  backend:
    build: 
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend/scoring-app
      dockerfile: frontend.scoring-app.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    restart: unless-stopped